### ISSUE TITLE
Crash on rotate when edittext focused on a scrollable listview

### ISSUE THREAD

**Issue by ataulm** [ataulm/stacks#14]
When the list is long enough to scroll and the edit text has focus, when you rotate, there is a crash (the edittext is set as a footer on the listview).

```
03-09 21:44:14.985    2599-2599/com.ataulm.stacks.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ataulm.stacks.debug, PID: 2599
    java.lang.IllegalArgumentException: parameter must be a descendant of this view
            at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:4548)
            at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:4485)
            at android.view.ViewRootImpl.scrollToRectOrFocus(ViewRootImpl.java:2660)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2304)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ataulm** [comment]
AND the soft keyboard must be open. If the keyboard is closed, no crash -> ensure the keyboard is closed prior to a rotate, and all will be dandy...

**Comment by peddintiprasanna** [comment]
This is way it is working for me
private class MyScrollListener implements OnScrollListener {

```
    @Override
    public void onScroll(AbsListView view, int firstVisibleItem,
            int visibleItemCount, int totalItemCount) {
        // do nothing 
    }

    @Override
    public void onScrollStateChanged(AbsListView view, int scrollState) {
        if (SCROLL_STATE_TOUCH_SCROLL == scrollState) {
            View currentFocus = mainActivity.getCurrentFocus();
            if (currentFocus != null) {
                currentFocus.clearFocus();
            }
        }
    }
}
```

listview.setOnScrollListener(new MyScrollListener());

**Comment by ataulm** [comment]
@peddintiprasanna Thanks! I haven't worked on stacks in a while, but may return to it shortly.
